- name: Leave swarm for a node
  shell: sudo docker swarm leave -f
  ignore_errors: yes


# - debug:
#     msg: "{{hostvars[groups['COMP90024'][0]]}}"

- name: "set worker token fact"
  set_fact:
    worker_token: "{{ hostvars[groups['COMP90024'][0]]['worker_token']['stdout'] }}"

- name: "set manager fact"
  set_fact:
    manager: "{{ groups['COMP90024'][0] }}"

- name: "join as a worker"
  shell: "sudo docker swarm join --token {{worker_token}} {{manager}}:2377"
  retries: 3
  delay: 20

