- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: COMP90024
  gather_facts: true
  become: yes
  roles:
    - role: setup-proxy
    - role: instance-common
    - role: docker
    - role: couchdb-volumes
    - role: couchdb


- hosts: COMP90024[0]
  gather_facts: no
  become: yes
  roles:
    - role: setup-cluster
    - role: setup-react-app
    - role: setup-crawler-city
    - role: setup-old-tweets-crawler
    - role: setup-ts-server
    - role: setup-classification-model
    - role: setup-analyser

- hosts: COMP90024
  gather_facts: yes
  become: yes
  roles:
    - role: setup-crawler