# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 10
  - vol_name: vol-2
    vol_size: 10
  - vol_name: vol-3
    vol_size: 10
  - vol_name: vol-4
    vol_size: 10
  - vol_name: vol-5
    vol_size: 10
  - vol_name: vol-6
    vol_size: 10

# Security group
security_groups:
  - name: ssh_22
    description: "Demo security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http_80
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: https_443
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: couchdb_5984
    description: "DB security group for Couch DB"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 65500
    remote_ip_prefix: 0.0.0.0/0
  - name: swarm_2377
    description: "SWARM security group"
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: server1
    volumes: ['vol-1', 'vol-2']
  - name: server2
    volumes: ['vol-3', 'vol-4']
  - name: server3
    volumes: ['vol-5', 'vol-6']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: id_xin
instance_flavor: uom.mse.1c4g

