---
- name: Create ts server directory
  tags: 'ts-server'
  become: yes
  file:
    path: "{{ ts_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Configure compose
  tags: 'ts-server'
  become: yes
  template:
    src: docker-compose.yaml.j2
    dest: "{{ ts_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Run docker compose
  tags: 'ts-server'
  become: yes
  docker_compose:
    project_src: "{{ ts_dir }}"
    pull: yes
    state: present
    remove_orphans: yes
    recreate: always