---
- name: Create CouchDB dir
  tags: 'couchdb'
  become: yes
  file:
    path: "{{ couch_db_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory

- name: Create CouchDB data dir
  tags: 'couchdb'
  become: yes
  file:
    path: "{{ couch_db_data_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes
    state: directory


- debug:
    msg: "ips in CMP90024 {{ groups['COMP90024'] }}"

- name: Configure compose
  tags: 'couchdb'
  become: yes
  template:
    src: docker-compose.yml.j2
    dest: "{{ couch_db_dir }}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Deploy CouchDB
  shell: sudo docker stack deploy -c {{ couch_db_dir }}/docker-compose.yml couchdb
  become_method: sudo
